# Site settings
title: Shanmugam Ekambaram
twitter_username: shanspaniard
name: Shanmugam Ekambaram

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
# primarylinks:
#  - title: Blog
#    url: http://automateddeveloper.blogspot.com/
#  - title: GitHub
#    url: https://github.com/robhinds
#  - title: StackOverflow
#    url: http://stackoverflow.com/users/258813/rhinds
#  - title: DZone
#    url: https://dzone.com/users/899489/rhinds.html
#  - title: LinkedIn
#    url: https://www.linkedin.com/pub/rob-hinds/21/361/3b1

#Any buzzword skills you want to include
skills:
 - Java
 - Big Data
 - SQL
 - REST API
 - MEAN

#Blogfeed is optional - including this will add JS to call the feed and populate blog list
# blogfeed: http://automateddeveloper.blogspot.com/feeds/posts/default?alt=rss

#Work experience is required
roles:
 - title: Big Data Analyst
   start: 2017
   end: Ongoing
   employer: Knoinf Technologies
   role: loading and transforming of large sets of structured and semi structured data.Develop Hive queries for the analysis of data.Set performance tuning parameters to increase overall performance.Migrating the data to MySql from Hive using Sqoop.Writing the design and technical documentation of the solution for the client

 - title: Software Engineer
   start: 2016
   end: 2017
   employer: CVIAC Consulting Pvt LTD
   role: Involved in requirement analysis,design and development.Developed data ingestion shell scripts to load data from source systems(MySql,SQL server) to hve using sqoop import commands.Import and Export data into hdfs and hive using sqoop.Load and transform large sets of structured and semi structured data.Involved in creating hive tables,loading data into hive tables and Writing hive queries.
   
 - title: Software Engineer
   start: 2013
   end: 2016
   employer: Viven Technologies
   role: Being one of the team member, worked Pro-actively and played vital role in collecting and consolidating client requirements.Involved in Analysis, Development and Unit Testing of CMS case management using Struts framework, JSP and Hibernate.Worked in Resolving and fixing errors on a daily basis occurs in production systems.Involved improving the performance in mainly used Search Screens like Provider and Member Search.

#Education is required
education:
 - level: Bachelor of Engineering (B.E)
   date : 2013
   subject: Computer Science
   college: Meenakshi college of Engineering
   university: Anna University
#This section is optional (as is the image link below)
coursera:
   profileurl: https://www.coursera.org/user/i/c6362b4056f755a04bef6a791a62102b
   courses:
    - title: Functional Programming Principles in Scala
      link: https://www.coursera.org/course/progfun
      optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/progfun/small-icon.hover.png
      date: September 16, 2013
    - title: Algorithms Design and Analysis, Part 1
      link: https://www.coursera.org/course/progfun
      optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/algo/small-icon.hover.png
      date: April 28, 2014

#List of interesting Github repo/projects to include - optional
github:
 - ShanmugamEkambaram/shanmugam.github.io
 - ShanmugamEkambaram/sparkRdd


#Stackoverflow flair is optional
stackoverflow:
   profileurl: http://stackoverflow.com/
   flairimageurl: http://stackoverflow.com/

#Mobile apps section is optional
apps:
 - name: 
   platform: Android
   url: https://play.google.com/store/apps/details?id=
   description:

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: 
  
